# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/

default_job = "check-test2"

[jobs.check-test2]
command = ["cargo", "check", "--color", "always", "--example", "test2"]
need_stdout = false
watch = ["examples"]
