[package]
name = "jugo"
version = "0.0.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
num-traits = "0.2"
vek = "0.16.1"
ignore = { git = "https://github.com/hiraginoyuki/rust-ignore" }

[profile.dev.package."*"]
opt-level = 3

# [dev-dependencies]
# criterion = "0.4"
# once_cell = "1"
